name: Website ci/cd
on: 
  push:
    branchs: [main]
  pull_reqeust:
    branchs: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
      env:
        prepo: ${{ github.repository }}
      steps:
      - uses: actions/checkout@main
      - name: Set up Minify action
        uses: amireshoon/minifyAction@main
        with:
          repo: $prepo
      - name: Minifying Soucre Code
        run: |
          minifier.sh $prepo
      - name: Pushing to the stage branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: github/workspace
          branch: stage 
 
