jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
      env:
        prepo: ${{ github.repository }}
      steps:
      - uses: actions/checkout@v2
      - name: Set up Minify action
        uses: amireshoon/minifyAction@main
        with:
          repo: $prepo
      - name: Minifying Soucre Code
        run: |
          minifier.sh $prepo
    ##  - name: Pushing to the production bracnh
        uses: actions-js/push@master
      ##  with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: github/workspace
          branch: production
          message: Minified Profolio Website HTML, CSS, JS
          author_name: MinifyAction[bot]
          author_email: amireshoon-minifyAction@sers.noreply.github.com
          force: true
